<?php $this->headTitle(_tr('About')); ?>
<h2><?php echo $this->translate('About mQueue'); ?></h2>
<p><?php echo $this->translate('This project started as a personal need in 2009. It is written in PHP and was an opportunity to explore Zend Framework, later migrated to <a href="https://docs.mezzio.dev/">Mezzio</a>, and <a href="http://jquery.com/">jQuery</a>. It also uses <a href="http://www.fatcow.com/free-icons/">FatCow\'s icon set</a>.'); ?>
</p>
<p><?php echo $this->translate('Source code is freely available <a href="https://github.com/PowerKiKi/mqueue">on GitHub</a>.'); ?>
</p>
