// ==UserScript==
// @name           mQueue - Injects buttons to rate IMDb movies on <?php echo $this->serverUrl('/') . PHP_EOL; ?>
// @namespace      mQueue
// @include        *
// @exclude        <?php echo $this->serverUrl('/'); ?>*
// ==/UserScript==

/*global document, XPathResult */

// Inject script if any links to IMDb found on the current page
if (document.evaluate('count(//a[contains(@href, "title/tt")])', document, null, XPathResult.NUMBER_TYPE, null).numberValue > 0)
{
    const script = document.createElement('script');
    script.src = '<?php echo $this->serverUrl('/js/remote.js'); ?>';
    document.getElementsByTagName('head')[0].appendChild(script);
}
