<?php $this->headTitle(_tr('FAQ')); ?>
<h2><?php echo $this->translate('FAQ'); ?></h2>
<dl class="faq">
    <dt><?php echo $this->translate('How does this work ?'); ?></dt>
    <dd><?php echo $this->translate('To get the most of this website, you should:'); ?>
        <ol>
            <li><a href="<?php echo $this->url(['controller' => 'user', 'action' => 'new']); ?>"><?php echo $this->translate('Create an account'); ?></a></li>
            <li>
                <ol>
                    <li class="browser_chrome"><?php echo $this->translate('For Chrome, skip to next step'); ?></li>
                    <li class="browser_firefox"><?php echo $this->translate('For Firefox, <a href="https://addons.mozilla.org/en-US/firefox/addon/748">install Greasemonkey</a>'); ?></li>
                    <li class="browser_safari"><?php echo $this->translate('For Safari, <a href="http://www.culater.net/software/SIMBL/SIMBL.php">SIMBL</a> and <a href="http://8-p.info/greasekit/">GreaseKit</a> should work'); ?></li>
                    <li class="browser_ie"><?php echo $this->translate('For IE, <a href="http://www.gm4ie.com">Greasemonkey for IE</a> may hopefully help'); ?></li>
                </ol>
            </li>
            <li><a href="<?php echo $this->baseUrl('js/mqueue.user.js'); ?>"><?php echo $this->translate('Install the user script'); ?></a></li>
            <li><?php echo $this->translate('Surf on <a href="http://www.imdb.com/">www.imdb.com</a> and rate movies by clicking icons'); ?></li>
        </ol>
    </dd>

    <dt><?php echo $this->translate('What is the meaning of the icons ?'); ?></dt>
    <dd><?php echo $this->statusHelp(); ?></dd>

    <dt><?php echo $this->translate("What happens if I click on others' icons ?"); ?></dt>
    <dd><?php echo $this->translate('Clicking on any icons you see will *always* vote for you. Never for someone else. So if you click on icons in someone else list, you will not immediately see the result, but you actually vote for yourself.'); ?></dd>

    <dt><?php echo $this->translate('How can I add more ratings options ?'); ?></dt>
    <dd><?php echo $this->translate('You cannot. It is meant to be a very simple, fast and efficient system. No extra bloating options.'); ?></dd>

    <dt><?php echo $this->translate('How to add a picture to my account ?'); ?></dt>
    <dd><?php echo $this->translate('Sign up for <a href="http://www.gravatar.com">www.gravatar.com</a> with the same email address and your picture will show up here.'); ?></dd>

    <dt><?php echo $this->translate('What about privacy ?'); ?></dt>
    <dd><?php echo $this->translate('Everything is publicly available for anyone. The only exceptions are emails and passwords which will never be published.'); ?></dd>
</dl>
