<h2><?php echo $this->translate('FAQ'); ?></h2>
<dl>
	<dt><?php echo $this->translate('How does this work ?'); ?></dt>
	<dd><?php echo $this->translate('To get the most of this website, you should:'); ?>
		<ol>
			<li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'new')); ?>"><?php echo $this->translate('Create an account'); ?></a></li>
			<li><a href="https://addons.mozilla.org/en-US/firefox/addon/748"><?php echo $this->translate('Install Greasemonkey'); ?></a></li>
			<li><a href="<?php echo $this->baseUrl('download/greasemonkey/mqueue.user.js'); ?>"><?php echo $this->translate('Install our Greasemonkey script'); ?></a></li>
			<li><?php echo $this->translate('Surf on '); ?><a href="http://www.imdb.com/">www.imdb.com</a></li>
		</ol>
	</dd>
	
	<dt><?php echo $this->translate('What is the meaning of the icons ?'); ?></dt>
	<dd><?php echo $this->statusHelp(); ?></dd>
	
	
	<dt><?php echo $this->translate('How can I add more ratings options ?'); ?></dt>
	<dd><?php echo $this->translate('You cannot. It is meant to be a very simple, fast and efficient system. No extra bloating options.'); ?></dd>
</dl>
