<?php use Application\Enum\Rating;

$this->headTitle(_tr('Users')); ?>
<h2><?php echo $this->translate('Users list'); ?></h2>
<table>
    <?php
    // Table header
    echo '<tr>';
echo '<th>' . $this->translate('User') . '</th>';
foreach (Rating::possibleChoices() as $rating) {
    echo '<th><span class="status current status_' . $rating->value . '" title="' . $rating->name() . '"><span>' . $rating->name() . '</span></span></th>';
}
echo '<th>' . $this->translate('Rated') . '</th>';
echo '<th>' . $this->translate('Not rated') . '</th>';
echo '</tr>';

// Table data
foreach ($this->users as $user) {
    echo '<tr>';
    echo '<td class="user"><a href="' . $this->url('user.view', ['id' => $user->id]) . '">' . $this->gravatar($user) . ' ' . $this->escapeHtml($user->nickname) . '</a></td>';
    $stats = $user->getStatistics();
    foreach (Rating::possibleChoices() as $rating) {
        echo '<td class="number"><a href="' . $this->url('movie.index') . '?filter1[user]=' . $user->id . '&amp;filter1[condition]=is&amp;filter1[status][]=' . $rating->value . '">' . $stats[$rating->value] . '</a></td>';
    }
    echo '<td class="number"><a href="' . $this->url('movie.index') . '?filter1[user]=' . $user->id . '&amp;filter1[condition]=isnot&amp;filter1[status][]=0">' . $stats['rated'] . '</a></td>';
    echo '<td class="number"><a href="' . $this->url('movie.index') . '?filter1[user]=' . $user->id . '&amp;filter1[condition]=is&amp;filter1[status][]=0">' . $stats[Rating::Nothing->value] . '</a></td>';
    echo '</tr>';
}
?>
</table>

<h2><?php echo $this->translate('Timeline'); ?></h2>
<?php echo $this->graph(); ?>
