language: php
php:
  - 7.1

addons:
  mariadb: '10.3'

before_script:
  - nvm install 10
  - nvm use 10
  - bin/install_dependencies.sh
  - yarn install
  - gulp

script:
  - ./vendor/bin/php-cs-fixer fix --diff --verbose --dry-run
  - ./vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload -vvv --format=php-clover clover.xml
