language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - scripts/install_dependencies.sh
  - npm install
  - gulp

script:
  - ./vendor/bin/php-cs-fixer fix --dry-run --verbose --diff --config-file .php_cs .
  - cd tests/ && phpunit --coverage-clover clover.xml && cd ../

after_script:
  - pwd
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload -vvv --format=php-clover tests/clover.xml

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
    - php: hhvm-nightly