language: php
sudo: false
php:
  - 7.1

before_script:
  - bin/install_dependencies.sh
  - npm install
  - gulp

script:
  - ./vendor/bin/php-cs-fixer fix --dry-run --verbose --diff --config-file .php_cs .
  - phpunit --coverage-clover clover.xml

after_script:
  - pwd
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload -vvv --format=php-clover clover.xml
