language: php
php:
  - "5.5"

before_script:
  - scripts/install_dependencies.sh
  - sudo npm install
  - gulp
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - cd tests/ && phpunit --coverage-clover log/clover.xml && cd ../
  - pwd
  - php ocular.phar code-coverage:upload -vvv --format=php-clover tests/log/clover.xml
