language: php
php:
  - "5.5"

before_script:
  - scripts/install_dependencies.sh
  - sudo npm install
  - gulp

script: cd tests/ && phpunit --coverage-clover log/clover.xml && cd ../

after_script:
  - pwd
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/log/clover.xml
