<?php $this->headTitle(_tr('Import')); ?>
<h2><?php echo $this->translate('Import votes from IMDb') ?></h2>
<?php if (!isset($this->movies)): ?>
    <?php echo $this->form; ?>
    <div class="tips">
        <?php
        echo $this->translate('See the %s to learn how to add movies directly from www.imdb.com in a single click !', [
            '<a href="' . $this->url(['controller' => 'faq'], null, true) . '">' . $this->translate('FAQ') . '</a>',
        ]);
        ?>
    </div>
<?php else: ?>
    <p><?php echo $this->translate('%1$s movies were imported successfuly. For details, see <a href="%2$s">your recent activity</a>.', [count($this->movies), $this->serverUrl() . $this->url(['controller' => 'activity', 'action' => 'index', 'user' => \mQueue\Model\User::getCurrent()->id])]) ?></p>
<?php endif; ?>