<?php

header('Content-type: text/csv');
header('Content-Disposition: attachment; filename="mQueue - ' . $this->translate('Movies') . '.csv"');
header('Expires: 0');
header('Cache-Control: must-revalidate, post-check=0,pre-check=0');
header('Pragma: public');

$out = fopen('php://output', 'w');

fputcsv($out, array($this->urlParams($this->permanentParams, false)));

$header = array();
foreach ($this->users as $user) {
    $header[] = $user->nickname;
}
$header[] = $this->translate('Title');
$header[] = $this->translate('Link');
fputcsv($out, $header);

foreach ($this->paginator as $entry) {
    $data = array();
    foreach ($this->users as $user) {
        $data[] = $entry->getStatus($user)->getName();
    }
    $data[] = $entry->getTitle();
    $data[] = $entry->getImdbUrl();
    fputcsv($out, $data);
}
fclose($out);
