<h2><?php echo $this->translate('Movies list'); ?></h2>
<table>
<tr>
	<th><?php echo $this->translate('Rating'); ?></th>
	<th><?php echo $this->translate('Title'); ?></th>
</tr>
<?php foreach ($this->entries as $entry): ?>
	<tr>
		<td><?php echo $this->statusLinks($entry->getStatus())?></td>
		<td><a href="<?php echo $entry->getImdbUrl(); ?>"><?php echo $this->escape($entry->getTitle()) ?></a></td>
	</tr>
<?php endforeach ?>
</table>

<p><a href="<?php echo $this->serverUrl() . $this->url(
    array(
        'controller' => 'movie',
        'action'     => 'add'
    ), 
    'default', 
    true) ?>"><?php echo $this->translate('Add movie'); ?></a></p>
<div><?php echo $this->statusHelp(); ?></div>