<?php

// Create array to store the RSS activity entries
$entries = [];

// Cycle through the rankings, creating an array storing
// each, and push the array onto the $entries array

foreach ($this->paginator as $movie) {
    $date = new Zend_Date($movie->dateUpdate);
    $text = '<p><a href="' . $movie->getImdbUrl() . '">' . $movie->getImdbUrl() . '</a></p>';

    foreach ($this->users as $user) {
        $status = $movie->getStatus($user);
        $text .= '<p><a href="' . $this->serverUrl() . $this->url([
                    'controller' => 'user',
                    'action' => 'view',
                    'id' => $user->id,
                        ], 'singleid', true) . '">' . $this->gravatar($user) . ' ' . $this->escape($user->nickname) . '</a> ' .
                $status->getName() . '</p>';
    }

    $title = $movie->getTitle();

    $entry = [
        'author' => 'mQueue',
        'title' => $title,
        'link' => $this->serverUrl() . $this->url(['controller' => 'movie', 'action' => 'view', 'id' => $movie->id], 'singleid', true),
        'description' => $title,
        'content' => $text,
        'lastUpdate' => $date->getTimestamp(),
    ];

    if ($movie->source) {
        $entry['enclosure'] = [
            [
                'url' => $movie->source,
                'type' => 'application/x-bittorrent',
            ],
        ];
    }

    array_push($entries, $entry);
}

// Create the RSS array
$rss = [
    'title' => 'mQueue - ' . $this->formFilter->getValuesText(),
    'link' => $this->urlParams($this->permanentParams),
    'charset' => 'UTF-8',
    'entries' => $entries,
];

// Import the array
$activity = Zend_Feed::importArray($rss, 'rss');

// Write the activity to a variable
$activity->send();
