<?php foreach (Default_Model_Status::$ratings as $name => $val): ?>
<a class="status status_<?php echo strtolower($name); if ($this->status->getRating() == $val) echo ' current';
?>" href="<?php echo $this->url(
		array(
			'controller' => 'status',
			'movie' => $this->status->getIdMovie(),
			'rating' => ($val == $this->status->getRating()) ? 0 : $val
		),
		'default', 
		true) ?>"><?php echo $name; ?></a><?php endforeach ?>