<?php foreach (Default_Model_Status::$ratings as $val => $name): ?>
<a class="status status_<?php echo strtolower($name); if ($this->status->rating == $val) echo ' current';
?>" href="<?php echo $this->serverUrl() . $this->url(
		array(
			'controller' => 'status',
			'movie' => $this->status->idMovie,
			'rating' => ($val == $this->status->rating) ? 0 : $val
		),
		'default', 
		true) ?>" title="<?php echo $name; ?>"><?php echo $name; ?></a><?php endforeach ?>