<?php

// Create array to store the RSS activity entries
$entries = array();

// Cycle through the rankings, creating an array storing
// each, and push the array onto the $entries array
foreach ($this->activity as $a) {
	$date = new Zend_Date($a['status']->dateUpdate);
	$text = '<p><a href="' . $this->serverUrl() . $this->url(array(
										'controller' => 'user',
										'action' => 'view',
										'id' => $a['user']->id
										),
									'default', true) . '">' . $this->gravatar($a['user']). ' ' . $this->escape($a['user']->nickname) . '</a> ' . 
			'<a href="' . $this->serverUrl() . $this->url(array(
										'controller' => 'movie',
										'action' => 'view',
										'idMovie' => $a['movie']->id
										),
									'default', true) . '">' . $this->escape($a['movie']->getTitle()) . '</a> ' .
			$a['status']->getName() . '</p>';
	$text .= '<p><a href="' . $a['movie']->getImdbUrl() . '">' . $a['movie']->getImdbUrl() . '</a></p>';
			
	$title = $this->escape($a['user']->nickname) . ' - ' . $this->escape($a['movie']->getTitle()) . ' - ' . $a['status']->getName();
		
	$entry = array(
		'author' => 'mQueue',
		'title' => $title,
		'link'=> $this->serverUrl() . $this->url(array('controller' => 'movie', 'action' => 'view', 'idMovie' => $a['movie']->id), 'default', true),
		'description' => $title,
		'content' => $text,
		'lastUpdate' => $date->getTimestamp()
	);
	array_push($entries, $entry);
}

// Create the RSS array
$rss = array(
	'title' => 'mQueue - ' . $this->title,
	'link' => $this->serverUrl() . $this->url(array()),
	'charset' => 'UTF-8', 
	'entries' => $entries
);

// Import the array
$activity = Zend_Feed::importArray($rss);

// Write the activity to a variable
$activity->send();

?>