<?php

// Create array to store the RSS activity entries
$entries = array();

// Cycle through the rankings, creating an array storing
// each, and push the array onto the $entries array

$cacheUser = array();
$cacheMovie = array();
foreach ($this->activity as $status)
{
	if (!array_key_exists($status->idUser, $cacheUser))
	{
		$cacheUser[$status->idUser] = Default_Model_UserMapper::find($status->idUser);
	}
	$user = $cacheUser[$status->idUser];

	if (!array_key_exists($status->idMovie, $cacheMovie))
	{
		$cacheMovie[$status->idMovie] = Default_Model_MovieMapper::find($status->idMovie);
	}
	$movie = $cacheMovie[$status->idMovie];


	$date = new Zend_Date($status->dateUpdate);
	$text = '<p><a href="' . $this->serverUrl() . $this->url(array(
										'controller' => 'user',
										'action' => 'view',
										'id' => $user->id
										),
									'singleid', true) . '">' . $this->gravatar($user). ' ' . $this->escape($user->nickname) . '</a> ' .
			'<a href="' . $this->serverUrl() . $this->url(array(
										'controller' => 'movie',
										'action' => 'view',
										'id' => $movie->id
										),
									'singleid', true) . '">' . $this->escape($movie->getTitle()) . '</a> ' .
			$status->getName() . '</p>';
	$text .= '<p><a href="' . $movie->getImdbUrl() . '">' . $movie->getImdbUrl() . '</a></p>';

	$title = $this->escape($user->nickname) . ' - ' . $this->escape($movie->getTitle()) . ' - ' . $status->getName();

	$entry = array(
		'author' => 'mQueue',
		'title' => $title,
		'link'=> $this->serverUrl() . $this->url(array('controller' => 'movie', 'action' => 'view', 'id' => $movie->id), 'singleid', true),
		'description' => $title,
		'content' => $text,
		'lastUpdate' => $date->getTimestamp()
	);
	array_push($entries, $entry);
}

// Create the RSS array
$rss = array(
	'title' => 'mQueue - ' . $this->title,
	'link' => $this->serverUrl() . $this->url(array()),
	'charset' => 'UTF-8',
	'entries' => $entries
);

// Import the array
$activity = Zend_Feed::importArray($rss, 'rss');

// Write the activity to a variable
$activity->send();
