<?php $this->headTitle($this->title); ?>
<h2><?php echo $this->escape($this->title); ?></h2>
<?php echo $this->activity($this->activity); ?>
<p class="alternateFormats"><?php echo $this->translate('Also available in:') ?> <a class="atom" href="<?php echo $this->urlParams(array('format' => 'atom')); ?>">Atom</a></p>

<?php echo $this->paginationControl($this->activity, null, null, array('permanentParams' => array())); ?>