<?php

// Create array to store the RSS activity entries
$entries = [];

// Cycle through the rankings, creating an array storing
// each, and push the array onto the $entries array

$cacheUser = [];
$cacheMovie = [];
foreach ($this->activity as $status) {
    if (!array_key_exists($status->idUser, $cacheUser)) {
        $cacheUser[$status->idUser] = \mQueue\Model\UserMapper::find($status->idUser);
    }
    $user = $cacheUser[$status->idUser];

    if (!array_key_exists($status->idMovie, $cacheMovie)) {
        $cacheMovie[$status->idMovie] = \mQueue\Model\MovieMapper::find($status->idMovie);
    }
    $movie = $cacheMovie[$status->idMovie];

    $date = new Zend_Date($status->dateUpdate);
    $text = '<p><a href="' . $this->serverUrl() . $this->url([
                'controller' => 'user',
                'action' => 'view',
                'id' => $user->id,
                    ], 'singleid', true) . '">' . $this->gravatar($user) . ' ' . $this->escape($user->nickname) . '</a> ' .
            '<a href="' . $this->serverUrl() . $this->url([
                'controller' => 'movie',
                'action' => 'view',
                'id' => $movie->id,
                    ], 'singleid', true) . '">' . $this->escape($movie->getTitle()) . '</a> ' .
            $status->getName() . '</p>';
    $text .= '<p><a href="' . $movie->getImdbUrl() . '">' . $movie->getImdbUrl() . '</a></p>';

    $title = $this->escape($user->nickname) . ' - ' . $this->escape($movie->getTitle()) . ' - ' . $status->getName();

    $entry = [
        'author' => 'mQueue',
        'title' => $title,
        'link' => $this->serverUrl() . $this->url(['controller' => 'movie', 'action' => 'view', 'id' => $movie->id], 'singleid', true),
        'description' => $title,
        'content' => $text,
        'lastUpdate' => $date->getTimestamp(),
    ];

    if ($movie->source) {
        $entry['enclosure'] = [
            [
                'url' => $movie->source,
                'type' => 'application/x-bittorrent',
            ],
        ];
    }

    array_push($entries, $entry);
}

// Create the RSS array
$rss = [
    'title' => 'mQueue - ' . $this->title,
    'link' => $this->serverUrl() . $this->url([]),
    'charset' => 'UTF-8',
    'entries' => $entries,
];

// Import the array
$activity = Zend_Feed::importArray($rss, 'rss');

// Write the activity to a variable
$activity->send();
