<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
  <title>mQueue</title>
  <?php 
  	echo $this->headLink()
  			->appendStylesheet($this->serverUrl() . $this->baseUrl('/css/global.css'))
  			->appendStylesheet($this->serverUrl() . $this->baseUrl('/css/layout.css'))
  			->appendStylesheet($this->serverUrl() . $this->baseUrl('/css/gravatar.css'));
  
	echo $this->headScript()	
			->prependFile($this->serverUrl() . $this->baseUrl('/js/script.js'))
			->prependFile($this->serverUrl() . $this->baseUrl('/js/jquery-1.4.min.js')); 
  ?>
</head> 
<body>
<div id="container">
	<div id="header">
		<?php echo $this->languageSelector(); ?>
		<div id="header-logo"><h1><a href="<?php echo $this->serverUrl() . $this->baseUrl(''); ?>"><?php echo $this->translate('mQueue'); ?></a></h1></div>
		<div id="header-navigation">
			<?php echo $this->navigation(); ?> 
			<?php echo $this->loginState(); ?> 
		</div>
	</div>
	<div id="content">
		<?php echo $this->layout()->content ?>
	</div>
	<div id="messages"><?php if (isset($this->messages)) foreach($this->messages as $message) echo '<p>' . $message . '</p>'; ?></div>
	<div id="footer">
	</div>
</div>
</body>
</html>
