<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
  <title>mQueue</title>
  <?php 
  	echo $this->headLink()
  			->appendStylesheet($this->serverUrl() . $this->baseUrl('/css/remote.css'))
  			->appendStylesheet($this->serverUrl() . $this->baseUrl('/css/local.css'))
  			->appendStylesheet($this->serverUrl() . $this->baseUrl('/css/gravatar.css'))
  			->appendAlternate($this->serverUrl() . $this->url(array('controller' => 'feed', 'format' => 'atom')), 'application/rss+xml', $this->translate('Overall activity'));
  
	echo $this->headScript()	
			->prependFile($this->serverUrl() . $this->baseUrl('/js/local.js'))
			->prependFile($this->serverUrl() . $this->baseUrl('/js/jquery-1.4.1.min.js')); 
  ?>
</head> 
<body>
<div id="container">
	<div id="header">
		<?php echo $this->languageSelector(); ?>
		<div id="header-logo"><h1><a href="<?php echo $this->serverUrl() . $this->baseUrl(''); ?>" title="<?php echo $this->translate('mQueue monster !'); ?>"><span><?php echo $this->translate('mQueue'); ?></span></a></h1></div>
		<div id="header-navigation">
			<?php echo $this->navigation(); ?> 
			<?php echo $this->loginState(); ?> 
		</div>
	</div>
	<div id="content">
		<?php echo $this->layout()->content ?>
	</div>
	<div id="messages"><?php if (isset($this->messages)) foreach($this->messages as $message) echo '<p>' . $message . '</p>'; ?></div>
	<div id="footer">
	</div>
</div>
</body>
</html>
