<?php
$lang = Zend_Registry::get(Zend_Locale::class)->getLanguage();
?><!doctype html>
<html lang="<?php echo $lang ?>">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width">
        <meta name="theme-color" content="#3679FF">
        <link rel="manifest" href="manifest.json">
        <?php
        echo $this->headTitle('mQueue')->setSeparator(' - ');
        echo $this->headLink([
                'rel' => 'icon',
                'href' => $this->serverUrl() . $this->baseUrl('/images/favicon.png'),
                'PREPEND',
            ])
                ->appendStylesheet('/css/application.css', 'all')
                ->appendStylesheet($this->serverUrl() . $this->baseUrl('/css/gravatar.css'), 'all')
                ->prependAlternate($this->serverUrl() . $this->url(['controller' => 'activity', 'action' => 'index'], 'activity', true) . '?format=rss&lang=' . $lang, 'application/rss+xml', $this->translate('mQueue - Overall activity'))
            . "\n";

        // Set localization file for timeago
        $path = '/js/min/jquery.timeago.' . $lang . '.js';
        if (is_file(APPLICATION_PATH . '/../public' . $path)) {
            $this->headScript()->prependFile($path);
        }

        echo $this->headScript()
            ->prependFile([
                '/js/min/application.js',
                [
                    '/js/application',
                ],
            ]);

        echo $this->googleAnalytics();
        ?>
    </head>
    <body>
        <div id="container">
            <div id="header">
                <?php echo $this->languageSelector(); ?>
                <?php echo new \mQueue\Form\QuickSearch(); ?>
                <div id="header-logo">
                    <h1><a href="<?php echo $this->serverUrl() . $this->baseUrl(''); ?>"
                           title="<?php echo $this->translate('mQueue monster !'); ?>"><span><?php echo $this->translate('mQueue'); ?></span></a>
                    </h1>
                    <span class="tagline"><?php echo $this->translate('never forget movies you want to watch'); ?></span>
                </div>
                <div id="header-navigation"><span>&nbsp;</span>
                    <?php echo $this->navigation()->menu(); ?>
                    <?php echo $this->loginState(); ?>
                </div>
            </div>
            <div id="content">
                <?php echo $this->flashMessenger(); ?>
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
        <div id="footer"><?php echo $this->footer(); ?></div>
    </body>
</html>
