<?php $this->headTitle(_tr('About')); ?>
<h2><?php echo $this->translate('About mQueue'); ?></h2>
<p><?php echo $this->translate('This project started as a personal need. It is written in PHP and is an opportunity to explore <a href="http://framework.zend.com/">Zend Framework</a> and <a href="http://jquery.com/">jQuery</a>. It also uses <a href="http://www.fatcow.com/free-icons/">FatCow\'s icon set</a>.'); ?>
</p>
<p><?php echo $this->translate('Source code is freely available on <a href="http://github.com/PowerKiKi/mqueue">http://github.com/PowerKiKi/mqueue</a>.'); ?>
</p>