/*global $, document, injectStatus */
(function(){
	<?php
	header('Content-type: application/javascript');
	header('Cache-Control: max-age=604800');
	header_remove('Pragma');
	header_remove('Expires');
	require_once(APPLICATION_PATH . '/../public/js/min/jquery-1.8.3.js');
	?>
	(function($){
		<?php require_once(APPLICATION_PATH . '/../public/js/min/both.js'); ?>

		$(document).ready(function()
		{
			$("head").append('<link href="<?php echo $this->cacheStamp('/css/both.css'); ?>" media="screen" rel="stylesheet" type="text/css" />');
			mqueue.monitorLinks('<?php echo $this->serverUrl() . $this->baseUrl('') ?>');
		});
	})(jQuery.noConflict(true));
})();
