/*global $, document, injectStatus */
(function(){
	<?php
	header('Content-type: application/javascript');
	require_once(APPLICATION_PATH . '/../public/js/min/jquery-1.8.3.js');
	?>
	(function($){
		var server = '<?php echo $this->serverUrl() . $this->baseUrl('') ?>';
		<?php require_once(APPLICATION_PATH . '/../public/js/min/both.min.js'); ?>

		$(document).ready(function()
		{
			$("head").append('<link href="' + server + 'css/both.css" media="screen" rel="stylesheet" type="text/css" />');
			mqueue.monitorLinks(server);
		});
	})(jQuery.noConflict(true));
})();
