<h2><?php echo $this->translate('Users list'); ?></h2>

<table>
<?php

// Table header
echo '<tr>';
echo '<th></th>';
foreach (Default_Model_Status::$ratings as $val => $name)
{
	echo '<th>' . $name . '</th>';
}
echo '<th>' . $this->translate('Not rated') . '</th>';	
echo '</tr>';

// Table data
foreach ($this->users as $user)
{
	echo '<tr>';
	echo '<td>' . $this->escape($user->nickname) . '</td>';
	$stats = $user->getStatistics();
	foreach (Default_Model_Status::$ratings as $val => $name)
	{
		echo '<td>' . $stats[$val] . '</td>';
	}
	echo '<td>' . $stats[Default_Model_Status::Nothing] . '</td>';
	echo '</tr>';
}
?>
</table>
<p><?php echo $this->translate('Total number of movie is %s', array($stats['total'])); ?></p>