<h2><?php echo $this->user->nickname; ?></h2>
<h3><?php echo $this->translate('Statistics'); ?></h3>

<table>
<?php 
$stats = $this->user->getStatistics();
foreach (Default_Model_Status::$ratings as $val => $name)
{
	echo '<tr><td>' .  $name . '</td><td><a href="' . $this->url(array(
										'controller' => 'movie',
										'action' => 'index',
										'filterUser' => $this->user->id,
										'filterStatus' => $val
										),
									'default', true) . '">' . $stats[$val] . '</a></td></tr>';
}
echo '<tr><td>' .  $this->translate('Not rated') . '</td><td><a href="' . $this->url(array(
										'controller' => 'movie',
										'action' => 'index',
										'filterUser' => $this->user->id,
										'filterStatus' => 0
										),
									'default', true) . '">' . $stats[Default_Model_Status::Nothing] . '</a></td></tr>';
echo '<tr><td>' .  $this->translate('Total') . '</td><td><a href="' . $this->url(array(
										'controller' => 'movie',
										'action' => 'index',
										'filterUser' => $this->user->id,
										'filterStatus' => -1
										),
									'default', true) . '">' . $stats['total'] . '</a></td></tr>';
?>
</table>

<h3><?php echo $this->translate('Recent activies'); ?></h3>
<?php echo $this->activity($this->user->getActivity()); ?>