<?php $this->headTitle($this->user->nickname); ?>
<?php echo $this->gravatar($this->user, 'big'); ?>
<h2><?php echo $this->escape($this->user->nickname); ?></h2>
<h3><?php echo $this->translate('Statistics'); ?></h3>

<table>
    <?php
// Table header
    echo '<tr>';
    foreach (\mQueue\Model\Status::$ratings as $val => $name) {
        echo '<th><span class="status current status_' . $val . '" title="' . $name . '"><span>' . $name . '</span></span></th>';
    }
    echo '<th>' . $this->translate('Rated') . '</th>';
    echo '<th>' . $this->translate('Not rated') . '</th>';
    echo '</tr>';

    $stats = $this->user->getStatistics();
    echo '<tr>';
    foreach (\mQueue\Model\Status::$ratings as $val => $name) {
        echo '<td class="number"><a href="' . $this->url([
            'controller' => 'movie',
            'action' => 'index',
                ], 'default', true) . '?filter1[user]=' . $this->user->id . '&amp;filter1[condition]=is&amp;filter1[status][]=' . $val . '">' . $stats[$val] . '</a></td>';
    }
    echo '<td class="number"><a href="' . $this->url([
        'controller' => 'movie',
        'action' => 'index',
            ], 'default', true) . '?filter1[user]=' . $this->user->id . '&amp;filter1[condition]=isnot&amp;filter1[status][]=0">' . $stats['rated'] . '</a></td>';
    echo '<td class="number"><a href="' . $this->url([
        'controller' => 'movie',
        'action' => 'index',
            ], 'default', true) . '?filter1[user]=' . $this->user->id . '&amp;filter1[condition]=is&amp;filter1[status][]=0">' . $stats[\mQueue\Model\Status::Nothing] . '</a></td>';
    echo '</tr>';
    ?>
</table>

<h2><?php echo $this->translate('Timeline'); ?></h2>
<?php echo $this->graph($this->user); ?>

<h3><?php echo $this->translate('Activity'); ?></h3>
<?php echo $this->activity($this->userActivity, ['user']); ?>

<?php
echo $this->alternateFormats([
    'rss' => $this->serverUrl() . $this->url(['controller' => 'activity', 'action' => 'index', 'user' => $this->user->id], 'activityUser', true),
        ], 'mQueue - ' . $this->translate('Activity for %s', [$this->user->nickname]));
?>
<?php echo $this->paginationControl($this->userActivity); ?>
